### ISSUE TITLE
Prevent screenshots functionality requires app restart

### ISSUE THREAD

**Issue by ljubitje** [EmmaTellblom/Mensinator#117]
Currently, prevent screenshots toggle works correctly, but requires app restart to start working.
Therefore the app will display setting one way but behave the other way, untill you restart it.

Ideally this would be implemented without needing to restart the app when the setting is toggled.
Alternatively, a popup warning can appear, informing the user and offering an app restart.

**Comment by EmmaTellblom** [comment]
It doesn't need a restart, but it needs to to change something like go to another page or change month or something, because that triggers a "refresh" but I get your point!
