### ISSUE TITLE
Import/Export Data buttons

### ISSUE THREAD

**Issue by ljubitje** [EmmaTellblom/Mensinator#119]
Currently the settings have duplicated text and unclear ui regarding the import/export functionality.

Since these functions do not have user set values, but trigger the import/export functionality, it'd be better to have them appear as buttons.
It'd be good to make a separate Import and export button side by side for clarity and to save the user from another popup or click.

![Screenshot_20240910-232126_Mensinator_1](https://github.com/user-attachments/assets/08f5fbd1-5a32-4dce-be6a-7669911a0aee)

**Comment by EmmaTellblom** [comment]
Fixed!
