### ISSUE TITLE
CreateNewSymptomDialog placeholder text is not using key

### ISSUE THREAD

**Issue by carstenhag** [EmmaTellblom/Mensinator#145]
The key symptom_name_label is not actually in use at the CreateNewSymptomDialog:

https://github.com/EmmaTellblom/Mensinator/blob/ebb0f91986238e4ca01803c1643b75c841ce6d26/app/src/main/java/com/mensinator/app/SymptomDialogs.kt#L118

![chrome_yYtQVIJe6Q](https://github.com/user-attachments/assets/c4faefad-ad07-404e-be6e-173279b7b21f)

**Comment by EmmaTellblom** [comment]
Fixed in PR #155
