### ISSUE TITLE
Protecting (encryption) the local database at rest

### ISSUE THREAD

**Issue by serrq** [EmmaTellblom/Mensinator#185]
Screenshot and idea taken from Molly (a foss Signal client).

![1000125879](https://github.com/user-attachments/assets/7d21a478-9632-43ea-91d0-286623de03af)

**Comment by carstenhag** [comment]
Questionable benefit. If someone is capable of extracting Mensinator's database from your phone, you have way way way way bigger problems anyhow, as then literally everything from your phone is readable.

For a messenger it may make sense to try to encrypt it (still doubtful imo), but here it seems unnecessary.

**Comment by carstenhag** [comment]
Again, if someone has physical access to your unlocked phone, you have way bigger problems. At that point, no encryption whatsoever can help you, because the attacker could just open the app (or make you open it).

**Comment by tomdavidson** [comment]
In the US, CBP can copy your phone data but they can't force you to decrypt without a warrant. My password manager bitwarden is encrypted and my OTP app has a separate encryption and pin than my phone.

I appreciate the goal of not selling data personal data to adtech and what not, but I think in today's legal climate a privacy respecting menstrual/period app needs to also be defensive by encrypting its user data.

**Comment by EmmaTellblom** [comment]
@tomdavidson Hi! I do agree with both sides, there are potential problems and complications with encrypting the database and if someone has access to your phone you probably have more serious issues than this data.

However, I am pondering adding some sort of encryption in the future but right now we are still focusing on basic functionalities such as making the app stable and working for a large user group.

I've also looked closer at CBP (out of curiosity) and while they are allowed to search your phone you are not obligated to unlock it (but refusing might cause you further issues). And they are only allowed to view the data, not store it anywhere.

They are allowed to copy phone data if they have approval from a supervisor and there is a reasonable suspicion of law violations or national security.
