### ISSUE TITLE
Add Github issue templates to the repo

### ISSUE THREAD

**Issue by carstenhag** [EmmaTellblom/Mensinator#189]
Create short templates so that we have an easier overview of tickets/etc. Labels can also automatically be set.

Example: https://github.com/carstenhag/darfichkiffen-android/tree/master/.github/ISSUE_TEMPLATE & https://github.com/carstenhag/darfichkiffen-android/issues/new/choose

**Comment by EmmaTellblom** [comment]
Created a PR with a first draft of what it could look like.
