### ISSUE TITLE
In Calendar view add possibility to switch months by pressing volume keys

### ISSUE THREAD

**Issue by serrq** [EmmaTellblom/Mensinator#191]
![1000125892](https://github.com/user-attachments/assets/ba2e5277-bb41-4a82-9ae7-5d8bec4ab5ad)

**Comment by carstenhag** [comment]
I guess this would need to be a by-default-off setting, because it is certainly not expected.

Also, Google Calendar does not support this (also not as option), so imo we should reject it. @EmmaTellblom

**Comment by EmmaTellblom** [comment]
Hi @serrq!
Thanks for your creative suggestion, all feedback and ideas are welcome. But I do agree with @carstenhag here that this is not common behavior and not expected. We have talked about adding swiping motion to change months though.
So I'm closing this issue for now, but please reach out if you have anymore suggestions or feedback.
