### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [EmmaTellblom/Mensinator#196]
1.9.2 tag is on 12579b4a4c35b8a72f47f9ab4324cf96c9daa7c5 but the version code of your apk is 22. And it's not built from 7261bfb415937c99e113de949c5351837ce1afd6 according to the vcs info in the apk. So I guess you bumped the version code then built the apk before committing the change.

**Comment by EmmaTellblom** [comment]
@linsui Yes you are right, my mistake! I made a new smaller release now, 1.9.3 where I made sure to commit first and then build. Hope it solved the issue on your end, otherwise let me know!
