### ISSUE TITLE
Sliding calendar? 

### ISSUE THREAD

**Issue by EmmaTellblom** [EmmaTellblom/Mensinator#20]
Instead of clicking previous or next, what if you instead could move the calendar with a swipe? Flow has a calendar that can be moved up and down for example. Would be easier to see if a period goes over the end of one month and the beginning of the next.

**Comment by carstenhag** [comment]
I have implemented a basic swipe, but the UX is not good. The user doesn't have feedback on the gesture. There should be some kind of indication. I'd be glad for some ideas.

WIP PR: #170

https://github.com/user-attachments/assets/a8a5a983-c7d4-41f9-b69b-f439d1277400
