### ISSUE TITLE
Add ability to pick a different app icon

### ISSUE THREAD

**Issue by Metaroll** [EmmaTellblom/Mensinator#208]
**Is your feature request related to a problem? Please describe.**
Some users might want to hide the fact that they are using a period tracking app from other people.
The default app icon makes it clear what the purpose of the app is, which is good for most users but not for the above.

**Describe the solution you'd like**
The Signal messaging app has a few built-in icons such as a generic "Weather" or "News" icon which masks the intent of the app from others, whilst letting the user continue to use the app normally (see screenshot below). Mensinator could copy this approach.
(Signal also changes the app title as well)
This setting could also prompt users to disable notification permissions for the app as well, if they want to.

**Describe alternatives you've considered**
Users could configure a custom icon launcher to change the app icon and disable app titles.
However this could be too much work for an average user, and it might be apparent to anyone monitoring the phone.
I don't think custom icons are possible on iOS either, so this method wouldn't work if/when Mensinator is added to the app store.

**Additional context**
Example from Signal
![signal icons](https://github.com/user-attachments/assets/132d6e8c-b40f-4e20-88ab-392e1ceae1cc)

**Comment by EmmaTellblom** [comment]
I get what you are saying but this is really farfetched and out of scope for the app. Of course the main purpose of this app is privacy but if someone already has your phone you are compromised either way. Regardless of the app icon or app name. And I don't really agree with the app being compared to signal as they have totally different purposes. This is something we will not implement.

**Comment by Metaroll** [comment]
Cool, makes sense

**Comment by carstenhag** [comment]
Android 15 allows you to hide apps. This is what the user should use.

**Comment by Metaroll** [comment]
@carstenhag didn't know about that feature lol, that does seem easier
