### ISSUE TITLE
[Additional Request] Add RU language

### ISSUE THREAD

**Issue by eXense-auth** [EmmaTellblom/Mensinator#212]
[values-ru.zip](https://github.com/user-attachments/files/18099231/values-ru.zip)
please )))

**Comment by EmmaTellblom** [comment]
@eXense-auth Thank you so much for translating the app to Russian! I have added your translations now, so next release they will be included! I do not have a date yet for when this will be though... But really appreciate your help in improving the app and making it accessible for more people!
