### ISSUE TITLE
APK for download

### ISSUE THREAD

**Issue by IzzySoft** [EmmaTellblom/Mensinator#43]
Hi Emma, I was approached to please include your app with the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid), so I came here to check. Unfortunately, you do not (yet) [tag your releases](https://github.com/EmmaTellblom/Mensinator/releases) and do not provide the APK there, so I cannot even check if it meets the [IzzyOnDroid App Inclusion Policy](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Inclusion-Policy).

I gladly give it a look and help out there, which also should meet your wish to [get word out](https://www.reddit.com/r/fossdroid/comments/1ebqkye/new_app_for_period_tracking_without_data_sharing/), as the mentioned repo has some popularity meanwhile. So if you agree, I'd guide you through the steps there and, if possible, get your app listed – at the IzzyOnDroid repo, and if you want to fulfill [the "literal wish"](https://www.reddit.com/r/fossdroid/comments/1ebqkye/comment/lewgl4r/) as well, also give hints to apply at F-Droid.org itself.

Looking forward to your reply!

**Comment by EmmaTellblom** [comment]
Hi, I will fix this next time I do a release for Google Play, which hopefully will be in a few weeks. I will ping you when it's done.

**Comment by IzzySoft** [comment]
Wonderful, thanks! Looking forward to that :star_struck:

**Comment by giankenbellfore** [comment]
Downloading an APK (Android Package Kit) file can be a convenient way to access apps that might not be available through the official Google Play Store. APK files[ sportzfy latest version](https://sportzfy-apk.com/) allow you to install apps directly on your Android device, often providing early access to new features or updates. However, it's important to exercise caution when downloading APK files.

**Comment by EmmaTellblom** [comment]
@IzzySoft 
Version 1.8.0 is now released and APK is available!

**Comment by EmmaTellblom** [comment]
@IzzySoft I'll take a look at this tomorrow. I know my code inside and out, we do not use Google maps and I'm pretty sure we don't use Firebase either. Must be some sort of reference somewhere in that case. And all the data is stored on the device and nothing is sent anywhere.
We who are working on the app are new to android development so ofc we can make mistakes. But I'll get back to you when I have looked at this!

**Comment by obfusk** [comment]
You're depending on [`com.google.android.libraries.places`](https://github.com/EmmaTellblom/Mensinator/blob/6ba4451907d442278c17570609811db97a2f4ee0/gradle/libs.versions.toml#L33). Maybe that was unintended?

**Comment by EmmaTellblom** [comment]
@obfusk Thanks for helping out! Im not sure why/when places was added as a lib but it was most definitely unintended. It was never used in the code...

@IzzySoft I cleaned the project and rebuild an APK and I cannot see these dependencies anymore. I don't understand where/why places was in there because I have never played around with any form of location data, not in any app... Firebase I think might have been left in there when I built the notification-stuff but I specifically wanted to avoid using it, I suspect the dependency didn't go away... 
I do not take offense, I take this as a learning opportunity! So thank you for pointing this out. New APK will be uploaded now and new release too.

**Comment by IzzySoft** [comment]
Thanks Emma! Probably "dependency hell", and Firebase was dragged in by e.g. Maps which was dragged in by Places or something (I didn't check the dependency tree, so please do not take this literally – but such "cascades" can be seen sometimes).

Confirming the new APK looking fine! :partying_face: Integrating it now at IzzyOnDroid… And Congrats, it's even a [Reproducible Build](https://reproducible-builds.org/) :partying_face: (see e.g. [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) for some background on this). So here's a preview from our staging area:

![image](https://github.com/user-attachments/assets/bbaecc8f-23d3-4888-bb91-a2f8d4f7be2b)

Your app should [show up here](https://apt.izzysoft.de/packages/com.mensinator.app) with the next sync around 6 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. And if you wish, I can send you a PR with the metadata (app description, graphics) in Fastlane format, so you'd be in control how your app is presented (you can use the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for guidance there; Fastlane would then be pulled along with each new release – and no binaries needed, just the metadata files). Just let me know and I send in the PR.

But now: Welcome aboard IzzyOnDroid! :partying_face: – and thanks a lot for your efforts! Will now notify the person who approached me with this wish, she will be very happy! :hugs:

**Comment by IzzySoft** [comment]
I see you've opened an RFP with F-Droid – and the bot said you're missing … Fastlane :stuck_out_tongue_winking_eye: My above offer still stands, @EmmaTellblom :wink:

**Comment by EmmaTellblom** [comment]
@IzzySoft Lol, I was so happy about being approved for IzzyOnDroid that I kind of skipped the last of your message. Sorry, I'll do better! And the funny part is that at the same time you wrote here I actually did include a fastlane because it wasn't so messy as I first thought it would be.

**Comment by obfusk** [comment]
> Thanks for helping out!

The IzzyOnDroid team is always happy to help :)

**Comment by IzzySoft** [comment]
> I actually did include a fastlane

Now, then let's turn my offer the other way round, and I update the YAML for Mensinator here to **use** it instead: with the next release, it will pull your Fastlane along :smiley: I'm pretty curious how your full description will render. IoD will convert it from Markdown to HTML, then replace all headings (h1…h6) with bold paragraphs (h1-h3 should also be made a little bigger) to not destroy page structure, sanitize it, and then import the result. Please take a look once the next release is out and let me know if you like it – or if we need…

…corrections. Which we will – not for IoD, but for F-Droid, which does not understand Markdown. So while above described results will look fine at IoD, F-Droid will simply replace each newline with a `<br>`, and ship it as such. You probably won't like that.

Two solutions for that, both described in the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane):

* use fully-fledged HTML and "compress" it so it's all on one line (so nowhere to replace newlines)
* use what the documentation describes as "Markdown Lite" – which renders fine at IoD, F-Droid and even Play.

**Comment by EmmaTellblom** [comment]
@IzzySoft I did change to HTML now, but you say it needs to be all in one-line? That seems weird... Can you please look and see if current file is good enough for Fdroid? I really appreciate you helping out!

**Comment by IzzySoft** [comment]
> but you say it needs to be all in one-line?

It does not NEED to. For F-Droid, not having it in a single line means they replace each and every newline by `<br>`, which will simply look… err… not that well. At IzzyOnDroid that's taken care for when Fastlane is being pulled, we have extra configuration for that (as we have to configure the "entry point"). Here's what is set up for Mensinator currently:

```yaml
  Fastlane: https://github.com/EmmaTellblom/Mensinator/blob/main/fastlane/metadata/android
  FastlaneFeatures: title,shortdesc,fulldescMD,icon,screenshots
```

First line is where the entry-point for your fastlane tree is to be found. Second line is what features are enabled and in which variant. You see e.g. `fulldescMD` there; that means "take the `full_description.txt`, then run it through the Markdown parser, then do the HTML sanitizing". That works with "full HTML" as well – but I could change it to `fulldesc` now to skip the Markdown part (which won't interfere as it allows for HTML, it's just not needed anymore if you have "full HTML") – but I guess I'll leave it in nevertheless so nothing breaks should you one day switch back). Sanitizing HTML also includes "compressing" it to a single line, so the fdroidserver software finds no newlines to replace.

> Can you please look and see if current file is good enough for Fdroid?

(Looking) at the current `HEAD` here it's still Markdown. At F-Droid you'd see an additional empty line below your "headings" (`<h1>` and `<h2>`) as those are block-level elements and thus already imply a line break themselves. All else would be handled as "plain text". I'm curious how the framework at IzzyOnDroid handles it: it uses "standard markdown" (so no flavors) and thus usually expects an empty line before and after bullet-point lists – except when they directly follow a "heading", so it should be fine. Btw, the sanitizer here will replace your `<h1>` and `<h2>` by something equivalent to `<p style='font-weight:bold;font-size:bigger'>`, so they don't break the structures of where the description is shown INLINED. h4-h6 would just be "bold" without increasing font size.

While here: your last release is RB again, but only after manual adjustment: you've built the APK **before** you committed your changes. Please always build the **release APKs** on a clean tree **after** all code is committed.

And speaking about builds: could you also include the gradle wrapper JAR next to the `gradle/wrapper/gradle-wrapper.properties`? Currently, the recipe for the verification builder(s) has to inject the gradle-bin indicated by the properties, but parsing that is not always safe. Better you have that set up fully here, then we can rely on your setup. Thanks in advance!

**Comment by EmmaTellblom** [comment]
@IzzySoft Thank you so much! I have included the gradle wrapper JAR and have tried to follow your other recommendations too!

**Comment by IzzySoft** [comment]
Thanks a lot, Emma! Will adjust the recipe at the verification builder with the next update then :star_struck:

**Comment by IzzySoft** [comment]
@EmmaTellblom you forgot to attach the APK to the latest release. And @obfusk just tells me you seen to have used an older wrapper than gradle version. She says you might wish to take a look at https://github.com/marketplace/actions/gradle-version-wrapper-update

**Comment by EmmaTellblom** [comment]
@IzzySoft Crap you are right.... I need to start making a checklist soon, lol. I will check out the github action tomorrow! I have corrected the new version at least.

**Comment by IzzySoft** [comment]
Thanks! As we use to say: SHIFT happens (eh, sorry, just got my new [SHIFTsound BNO](https://shop.shiftphones.com/shiftsound-bno.html) and am excited about the sound quality – and "SHIFT happens" is their slogan. A really nice (family-) company with exciting products, I'm much convinced and highly recommend them. Also using 2 of their phones meanwhile)… oops, apologies for the fill-in :see_no_evil:

Yeah, we'll see then. Just attach the APK for the current version (Fay says the wrapper should still work, despite of not being the most recent). And the next release then will have it all completed. Thanks a lot for all your hard work there, Emma! :heart_eyes:

**Comment by IzzySoft** [comment]
Oops, APK was already attached meanwhile… So the updater probably caught it. Hurry, Izzy! (bit action behind the scenes) OK, adjusted the commit again :see_no_evil: OK, it's RB :sweat_smile: (pushing the logs) and the green shield should be up again :smiley:

**Comment by IzzySoft** [comment]
@EmmaTellblom please always build the app from a clean tree at the commit your tag points to. I had quite a bit to juggle getting your current release reproducible:

```bash
git checkout 7261bfb415937c99e113de949c5351837ce1afd6     # that is where your last changes ended up
git reset --soft 12579b4a4c35b8a72f47f9ab4324cf96c9daa7c5 # the embedded commit hash
```

Maybe I should simply have used `sed` to apply your changes :see_no_evil: However, this means the next release will need manual adjustments as well (removing those two lines again)…

**Comment by EmmaTellblom** [comment]
@IzzySoft So sorry for the inconvenience, I really should create a checklist as I said I would in August... I will try and see if I can improve my releases so you do t have to fix them in the future!

**Comment by IzzySoft** [comment]
Thanks Emma! And no worries, this was a rather easy one (you can bet I get "uglier ones" every week, which I cannot fix myself – like "commit – change something – build APK – change something else – commit, tag"; have fun if that were several lines in some code and not just the `versionCode` in the `build.gradle` :see_no_evil:). So I rather mentioned it as a reminder, before… well, no, not giving bad ideas here :rofl:
