### ISSUE TITLE
Swiping in the calendar 

### ISSUE THREAD

**Issue by EmmaTellblom** [EmmaTellblom/Mensinator#60]
Add ability to swipe to change months in the calendar.
So users can choose how to switch months by using both swiping or clicking the buttons.

**Comment by ljubitje** [comment]
Is this common? Can it be done on title area of calendar only?
It annoys me so much when I accidentally do something, like swipe a track away in Spotify for example.

**Comment by EmmaTellblom** [comment]
duplicate issue
