### ISSUE TITLE
One hand navigation bar (placed at the bottom)

### ISSUE THREAD

**Issue by serrq** [EmmaTellblom/Mensinator#68]
UI is more comfortable to reach, especially if one has a 6.7" display. This setting is optional (on/off toggle placed somewhere).

![1000117843](https://github.com/user-attachments/assets/94302647-c63f-42d9-8091-af68d645a2ef)

**Comment by EmmaTellblom** [comment]
Hmm, I'm not really sure what toolbar you want there? I know that there is an issue with big whitespace when the screen is bigger, but do you mean we should move the navigation bar at the bottom and move it up?

**Comment by EmmaTellblom** [comment]
Oh that's so kind if you! We welcome any questions/request no matter who you are. I'll add this for consideration when creating the new UI. If you want you can join our discord and help us out. We have several males helping us with different things!

**Comment by EmmaTellblom** [comment]
I understand what you are saying, but that is against the whole privacy point. The main point of this app is that your data is only stored locally on your phone and never leaves your phone. So it's not possible to share this kind of data. However, we do have an export and import feature that could be used to share data, but that would have to be used manually and you would probably be tired of it.

**Comment by EmmaTellblom** [comment]
This is already possible with the export and import option of the app. Ofc you would get all the data as there are no options to "hide" data. And sending through telegram would actually require Internet?
But she could export the data and then send through Bluetooth I think. So it is possible with current features of the app!

**Comment by thatBeatrice** [comment]
This implies that every time the girl enters data in the app, she has to send the file to her boyfriend, as Emma said. This routine might get annoying, even with modular backup.

About sending the file through a third party app, it could lead to privacy issues - a debatable matter. Anyone with access to phone and app (maybe they know/guess the code) could send themselves the file and gain insight to the target person's menstrual cycle. The import/export could scare off people with malicious intentions if they don't know how to transfer files between phones, or do it fast. That's my take 😆

**Comment by thatBeatrice** [comment]
I'd say that full privacy and sharing with other people (not necessarily a partner) don't go hand in hand.

**Comment by thatBeatrice** [comment]
Your idea is great! Though I don't think it's suitable for this app, when it promotes privacy. If people want this, they can compromise and turn to other apps - someone surely did it.

**Comment by EmmaTellblom** [comment]
Left to do;
Get the statistics working
Add import/export to settings
Add about to settings

Then we can remove the FAB.
