### ISSUE TITLE
Permission: internet

### ISSUE THREAD

**Issue by skariko** [EmmaTellblom/Mensinator#81]
hello,
I tried installing the app from both the Play Store and GitHub.

Having GrapheneOS operating system I get “notified” when an application requires internet access.

The bizarre thing I noticed is that the version on the Play Store requires internet access (also [confirmed by Exodus](https://reports.exodus-privacy.eu.org/it/reports/com.mensinator.app/latest/)) while the GitHub version does not. Is this intentional? Is there a particular reason?

Thanks!

**Comment by EmmaTellblom** [comment]
Hi!
Not intentional but a side-effect. We did some rework of the app to get it approved for FDroid and IzzyOnDroid after we launched version 1.8.0 to GooglePlay. So Github is several versions "ahead" of GooglePlay which you can see here:
https://github.com/EmmaTellblom/Mensinator/wiki
