### ISSUE TITLE
Add the different phases of the menstrual cycle 

### ISSUE THREAD

**Issue by Jgth6** [EmmaTellblom/Mensinator#91]
A good thing to add would be the other phases of the cycle follicular and luteal

**Comment by EmmaTellblom** [comment]
I think this is a duplicate of #18 ? Or did you mean to have this directly in the calendar or something?

**Comment by Jgth6** [comment]
Sorry yes it's a duplicate

**Comment by EmmaTellblom** [comment]
Really appreciate your feedback though! If you have any other suggestions, please submit a new issue and we'll look into it!
